# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

title: "Personal Website"
teaser: "/Resources/Images/teaser.jpg"
logo: " /assets/logo.jpg"
author:
  name     : "Hamid Taleghamar"
  bio      : "Passionate about AI, Machine Learning, and video games+🎸📚"
  avatar   : "/Resources/Images/avatar.jpg"
  location : "Toronto, Canada"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/raika96"
      links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/hamid-tale/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/hamidrt96"